"""Synthetic regressions for aggregate brim bounds hiding clear edge segments."""
import copy
import io
import json
import math
import os
from pathlib import Path
import random
import sys
import tempfile
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]/'extras'))
import ad5x_purge as p
from test_purge import PurgeHarness, gcode, Status

# Synthetic L, with a large empty corner inside its aggregate bounding box.
POLYGON = [(1,1),(219,1),(219,219),(175,219),(175,45),(1,45)]


def job(body=None, poly=POLYGON, header='G90\nM83'):
    if body is None:
        body = ('G1 X1 Y1\nG1 Z.25\n;WIDTH:0.5\n' +
                ''.join('G1 X%s Y%s E1\n' % v for v in poly[1:]+poly[:1]))
    return ('; generated by OrcaSlicer test\n'
            'EXCLUDE_OBJECT_DEFINE NAME=shape POLYGON='+json.dumps(poly)+'\n'+
            header+'\n;LAYER_CHANGE\n;Z:0.25\n'+body+
            '\n;LAYER_CHANGE\n;Z:1.50\n; print_sequence = by layer\n').encode()


def geometry(data=None, **kwargs):
    return p.parse_paths(io.BytesIO(job() if data is None else data),1.3,**kwargs)


def plan(g):
    return p.choose_edge(g,(0,0,220,220),30,.8,20)


def distance_point_segment(pt,a,b):
    d = (b[0]-a[0],b[1]-a[1])
    n = d[0]*d[0]+d[1]*d[1]
    t = max(0,min(1,((pt[0]-a[0])*d[0]+(pt[1]-a[1])*d[1])/n)) if n else 0
    return math.hypot(pt[0]-a[0]-t*d[0],pt[1]-a[1]-t*d[1])


class GeometryTests(unittest.TestCase):
    def test_interval_union_matches_independent_clipping_on_mixed_obstacles(self):
        # Clip each segment as a degenerate polygon for an independent oracle.
        # Include zero-length/parallel paths, overlapping buffers and margins.
        rng = random.Random(40137)
        for axis in (0, 1):
            for fixed in (3., 110., 217.):
                for radius in (0., 3., 20.02, 78., 120.):
                    geometry = {
                        'polygons': [[(40,40),(180,40),(180,80),(80,80),(80,180),(40,180)]],
                        'segments': [((50.,50.),(50.,50.),.5),
                                     ((-20.,3.),(240.,3.),.5),
                                     ((217.,-20.),(217.,240.),2.5)] +
                                    [((rng.uniform(-30,250),rng.uniform(-30,250)),
                                      (rng.uniform(-30,250),rng.uniform(-30,250)),
                                      rng.uniform(.5,2.5)) for _ in range(30)]}
                    other = 1-axis
                    expected = []
                    for poly, padding in ([(poly,radius) for poly in geometry['polygons']] +
                                          [([a,b],radius+width) for a,b,width in geometry['segments']]):
                        clipped = p.clip_polygon(poly,axis,fixed-padding,fixed+padding)
                        if clipped:
                            expected.append((min(v[other] for v in clipped)-padding,
                                             max(v[other] for v in clipped)+padding))
                    expected.sort()
                    for window in ((3.,217.,40.),(-40.,260.,10.),(30.,60.,5.)):
                        reference = p.free_intervals(expected,*window)
                        for bounded in (False,True):
                            actual = p.free_intervals(p.blocked_intervals(
                                geometry,axis,fixed,radius,
                                window=window if bounded else None),*window)
                            with self.subTest(axis=axis,fixed=fixed,radius=radius,
                                              window=window,bounded=bounded):
                                self.assertEqual(len(actual),len(reference))
                                for a,b in zip(actual,reference):
                                    self.assertAlmostEqual(a[0],b[0],places=8)
                                    self.assertAlmostEqual(a[1],b[1],places=8)

    def test_covered_paths_do_not_hide_a_buffer_protruding_past_polygon(self):
        geometry={'polygons':[[(0,0),(100,0),(100,100),(0,100)]],
                  'segments':[((90,50),(110,50),2.5)]}
        result=p.free_intervals(p.blocked_intervals(geometry,1,50,20),3,217,40)
        self.assertEqual(result,[(132.5,217)])

    def test_fully_blocked_window_stops_before_scanning_remaining_paths(self):
        def unused_paths():
            raise AssertionError('Extra paths cannot create a gap in a blocked window')
            yield
        geometry={'polygons':[[(0,0),(220,0),(220,220),(0,220)]],
                  'segments':unused_paths()}
        blocked=p.blocked_intervals(geometry,1,3,20,window=(3,217,40))
        self.assertEqual(p.free_intervals(blocked,3,217,40),[])

    def test_large_aggregate_bounds_still_have_clear_partial_edge(self):
        g=geometry();s=plan(g)
        self.assertIn(s['side'],('left','back'))
        self.assertGreaterEqual(s['clearance'],20.)
        self.assertEqual(g['layers'],1)

    def test_real_full_bed_square_has_no_clear_edge(self):
        with self.assertRaisesRegex(p.PlanError,'no clear edge'):
            plan(geometry(job(poly=[(1,1),(219,1),(219,219),(1,219)])))

    def test_brim_paths_protected_even_when_models_are_small(self):
        data=job('G1 X1 Y1\nG1 Z.25\nG1 X219 Y1 E1\nG1 X219 Y219 E1\n'
                 'G1 X1 Y219 E1\nG1 X1 Y1 E1',poly=[(80,80),(90,80),(90,90),(80,90)])
        with self.assertRaisesRegex(p.PlanError,'no clear edge'):plan(geometry(data))

    def test_synthetic_border_is_ignored_only_with_real_complete_paths(self):
        data=job().replace(b'G90',b'EXCLUDE_OBJECT_DEFINE NAME=BORDER1 POLYGON=[[0,0],[220,0],[220,220],[0,220]]\nG90')
        g=geometry(data);self.assertEqual(len(g['polygons']),1);self.assertGreater(plan(g)['clearance'],20)

    def test_low_travels_and_timelapse_return_corridor_are_protected(self):
        data=job('G1 X100 Y100\nG1 Z.25\nG1 X110 Y110 E1\n'
                 '_SET_TIMELAPSE_SETUP PARK_ENABLE=True\nTIMELAPSE_TAKE_FRAME\nG1 X1 Y210')
        g=geometry(data,park={'enabled':True,'park':False,'x':-20,'y':232})
        self.assertIn(((110.,110.),(-20,232),.5),g['segments'])
        self.assertIn(((110.,110.),(1.,210.),.5),g['segments'])

    def test_actual_low_layer_limit_includes_later_low_moves(self):
        data=job().replace(b';Z:1.50',b';Z:0.45\nG1 Z.45\nG1 X100 Y217\n;LAYER_CHANGE\n;Z:1.50')
        g=geometry(data);self.assertEqual(g['layers'],2)
        self.assertTrue(any(b==(100.,217.) for a,b,w in g['segments']))

    def test_absolute_e_relative_xy_and_e_reset(self):
        data=job('G1 X50 Y50\nG1 Z.25\nG1 X60 E1\nG92 E0\nG91\nG1 X10 E.2\nG90\nG1 X80 E.3',header='G90\nM82')
        g=geometry(data)
        self.assertEqual([b for a,b,w in g['segments']],[(60.,50.),(70.,50.),(80.,50.)])

    def test_unsupported_arcs_transforms_and_toolchanges_fail_closed(self):
        for cmd in ['G2 X50 Y50 I2 J2 E1','G92 X0','G20','SET_GCODE_OFFSET X10','T1','CUSTOM_MACRO']:
            with self.subTest(cmd=cmd),self.assertRaises(p.PlanError):
                geometry(job('G1 X50 Y50\nG1 Z.25\n'+cmd))

    def test_truncated_missing_modes_and_sequential_files_fail_closed(self):
        for data in [job().split(b';LAYER_CHANGE\n;Z:1.50')[0],
                     job().replace(b'by layer',b'by object'),job(header='G90'),
                     job().replace(b'; generated by OrcaSlicer test',b'; unknown')]:
            with self.subTest(data=data[:40]),self.assertRaises(p.PlanError):geometry(data)

    def test_nonfinite_or_malformed_polygon_is_rejected(self):
        with self.assertRaises(p.PlanError):geometry(job().replace(b'[1, 1]',b'[NaN, 1]',1))

    def test_search_clearance_independently_measured_on_random_obstacles(self):
        rng=random.Random(125)
        accepted=0
        for _ in range(60):
            g={'polygons':[], 'segments':[((rng.uniform(30,190),rng.uniform(30,190)),
                (rng.uniform(30,190),rng.uniform(30,190)),.5) for i in range(12)]}
            try:s=plan(g)
            except p.PlanError:continue
            accepted+=1
            for i in range(161):
                pt=(s['x']+s['dx']*i/4,s['y']+s['dy']*i/4)
                self.assertTrue(3<=pt[0]<=217 and 3<=pt[1]<=217)
                for a,b,w in g['segments']:
                    self.assertGreaterEqual(distance_point_segment(pt,a,b)-w,20.-1e-6)
        self.assertGreater(accepted,20)

    def test_length_includes_wipe(self):
        g=geometry()
        with self.assertRaises(p.PlanError):p.choose_edge(g,(0,0,40,40),30,.8,0)


class IntegrationTests(unittest.TestCase):
    def setUp(self):
        self.tmp=tempfile.TemporaryDirectory()
        self.path=Path(self.tmp.name)/'test.gcode';self.path.write_bytes(job())
        self.h=PurgeHarness((.2,.2,219.8,219.8))
        sd=self.h.objects['virtual_sdcard'];sd.sdcard_dirname=self.tmp.name
        sd.data.update(file_path=str(self.path),is_active=True,progress=.001)

    def tearDown(self):self.tmp.cleanup()

    def test_fallback_reached_via_native_macro_and_dispatch_and_dry_run_is_inert(self):
        self.h.objects['toolhead'].data['homed_axes']=''
        self.h.objects['extruder'].data['can_extrude']=False
        self.h.gcode.run_script('LINE_PURGE DRY_RUN=1')
        self.assertTrue(any('actual_paths=' in m for m in self.h.messages))
        self.assertFalse(any('Unknown command' in m for m in self.h.messages))
        self.assertEqual(self.h.motion,[]);self.assertEqual(self.h.commands,[])

    def test_full_fallback_motion_preserves_sensors_acceleration_and_e_state(self):
        before=self.h.move.get_status(1.)
        self.h.gcode.run_script('LINE_PURGE')
        self.assertGreater(len(self.h.motion),5)
        self.assertTrue(self.h.sensor_enabled);self.assertEqual(self.h.accel,20000)
        self.assertEqual(self.h.move.get_status(1.)['absolute_extrude'],before['absolute_extrude'])
        self.assertGreaterEqual(self.h.motion[-1][0][2],5)
        self.assertEqual(self.h.retracts,1)

    def test_explicit_filename_only_nonmoving_and_confined_to_sd_root(self):
        self.h.objects['virtual_sdcard'].data.update(file_path=None,is_active=False)
        self.h.gcode.run_script('PLAN_EDGE_PURGE DRY_RUN=1 FILE="test.gcode"')
        for cmd in ['PLAN_EDGE_PURGE FILE="test.gcode"',
                    'PLAN_EDGE_PURGE DRY_RUN=1 FILE="../elsewhere.gcode"']:
            with self.assertRaises(gcode.CommandError):self.h.gcode.run_script(cmd)
        self.assertEqual(self.h.motion,[])

    def test_malformed_file_and_inactive_print_do_not_move_or_change_sensors(self):
        self.path.write_bytes(b'invalid')
        with self.assertRaises(gcode.CommandError):self.h.gcode.run_script('LINE_PURGE')
        self.path.write_bytes(job())
        self.h.objects['virtual_sdcard'].data['is_active']=False
        with self.assertRaises(gcode.CommandError):self.h.gcode.run_script('LINE_PURGE')
        self.assertEqual(self.h.motion,[]);self.assertTrue(self.h.sensor_enabled)

    def test_nonzero_stationary_blob_refused_by_fallback(self):
        self.h.objects['gcode_macro _KAMP_Settings'].data['tip_distance']=5.
        with self.assertRaisesRegex(gcode.CommandError,'stationary blobs'):
            self.h.gcode.run_script('LINE_PURGE')
        self.assertEqual(self.h.motion,[])

    def test_cache_rechecks_file_content_even_if_size_and_mtime_are_preserved(self):
        self.h.gcode.run_script('LINE_PURGE DRY_RUN=1')
        self.h.gcode.run_script('LINE_PURGE DRY_RUN=1')
        self.assertIn('cached=1',self.h.messages[-1])
        stamp=self.path.stat()
        data=self.path.read_bytes().replace(b'by layer',b'by objct')
        self.path.write_bytes(data)
        os.utime(self.path,ns=(stamp.st_atime_ns,stamp.st_mtime_ns))
        with self.assertRaises(gcode.CommandError):self.h.gcode.run_script('LINE_PURGE DRY_RUN=1')
        self.assertEqual(self.h.motion,[])

    def test_cache_replans_after_margin_or_timelapse_changes(self):
        self.h.gcode.run_script('LINE_PURGE DRY_RUN=1')
        self.h.objects['gcode_macro _KAMP_Settings'].data['purge_margin']=21.
        self.h.gcode.run_script('LINE_PURGE DRY_RUN=1')
        self.assertIn('cached=0',self.h.messages[-1])


if __name__ == '__main__':unittest.main(verbosity=2)
